'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const project = path.resolve(__dirname, '..');
const repository = process.env.GITHUB_REPOSITORY || process.argv[2];
const publicKeyPath = process.argv[3];
const secret = process.env.ORB_UPDATE_PRIVATE_KEY;
if (!/^[A-Za-z0-9][A-Za-z0-9-]{0,38}\/[A-Za-z0-9][A-Za-z0-9._-]{0,99}$/.test(repository || '')) throw new Error('A real owner/repository is required');
let key;
if (secret) key = crypto.createPublicKey(crypto.createPrivateKey(secret));
else if (publicKeyPath) key = crypto.createPublicKey(fs.readFileSync(publicKeyPath));
else throw new Error('Supply public-key file argument or the protected ORB_UPDATE_PRIVATE_KEY environment secret');
if (key.asymmetricKeyType !== 'ed25519') throw new Error('Only Ed25519 signing keys are supported');
const publicKey = key.export({type:'spki',format:'pem'}).toString();
const current = JSON.parse(fs.readFileSync(path.join(project,'update-config.json'),'utf8'));
if (current.repository && current.repository !== repository) throw new Error('Configured repository differs; intentional migration requires a reviewed config change');
if (current.publicKey && crypto.createPublicKey(current.publicKey).export({type:'spki',format:'pem'}).toString() !== publicKey) throw new Error('Signing key differs from the pinned public key; do not silently rotate');
fs.writeFileSync(path.join(project,'update-config.json'),JSON.stringify({schema:1,repository,publicKey,channel:'stable'},null,2)+'\n');
console.log('Configured public release origin and public verification key; no private key was written.');
