'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const project = path.resolve(__dirname,'..');
const pkg = require('../package.json');
const config = JSON.parse(fs.readFileSync(path.join(project,'update-config.json'),'utf8'));
if (!/^(0|[1-9]\d{0,4})\.(0|[1-9]\d{0,4})\.(0|[1-9]\d{0,4})$/.test(pkg.version) || pkg.version.split('.').some(part => Number(part) > 65535)) throw new Error('Stable releases require an exact X.Y.Z version');
if (!config.repository || !config.publicKey) throw new Error('Configure repository and verification public key before signing');
if (process.env.GITHUB_REPOSITORY && process.env.GITHUB_REPOSITORY !== config.repository) throw new Error('Workflow repository does not match pinned repository');
if (process.env.GITHUB_REF_TYPE === 'tag' && process.env.GITHUB_REF_NAME !== 'v'+pkg.version) throw new Error('Release tag does not match package version');
const key = crypto.createPrivateKey(process.env.ORB_UPDATE_PRIVATE_KEY || '');
if (key.asymmetricKeyType !== 'ed25519') throw new Error('An Ed25519 release signing key is required');
const expected = crypto.createPublicKey(config.publicKey).export({format:'der',type:'spki'});
const actual = crypto.createPublicKey(key).export({format:'der',type:'spki'});
if (!expected.equals(actual)) throw new Error('Protected signing key does not match pinned public key');
const dir = path.resolve(process.argv[2] || path.join(project,'dist'));
const file = 'GPT-Orb-Setup-'+pkg.version+'-x64.exe';
const installer = path.join(dir,file);
const bytes = fs.readFileSync(installer);
if (bytes.length < 1024*1024 || bytes.subarray(0,2).toString() !== 'MZ') throw new Error('Installer is missing or is not a Windows executable');
const sha256 = crypto.createHash('sha256').update(bytes).digest('hex');
const sha512 = crypto.createHash('sha512').update(bytes).digest('base64');
const publishedAt = new Date().toISOString();
const descriptor = {schema:1,version:pkg.version,tag:'v'+pkg.version,platform:'win32',arch:'x64',file,size:bytes.length,sha256,sha512,publishedAt};
const payload = Buffer.from(JSON.stringify(descriptor),'utf8');
const envelope = {payload:payload.toString('base64'),signature:crypto.sign(null,payload,key).toString('base64')};
fs.writeFileSync(path.join(dir,'orb-update.json'),JSON.stringify(envelope,null,2)+'\n');
// Metadata is accepted only after the application verifies orb-update.json and checks all fields.
fs.writeFileSync(path.join(dir,'latest.yml'),`version: ${pkg.version}\nfiles:\n  - url: ${file}\n    sha512: ${sha512}\n    size: ${bytes.length}\npath: ${file}\nsha512: ${sha512}\nreleaseDate: '${publishedAt}'\n`);
fs.writeFileSync(path.join(dir,file+'.sha256'),sha256+'  '+file+'\n');
console.log('Signed release '+pkg.version+' ('+bytes.length+' bytes), public descriptor: orb-update.json');
